version: "3"

services:
  minor-project:
    build: ./flaskapp-docker
    ports: 
      - "8000:8000"
    network_mode: bridge
  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=13.126.66.61
    restart: always
    network_mode: bridge
